export interface FormErrorTrip {
  estatus: string
  observaciones_cancelacion: string
  tipo: string
  numero_cotizacion: string
  moneda: string
  tipo_viaje: string
  numero_trip: string
  metodo_pago: string
  forma_pago: string
  uso_CFDI: string
  fecha_salida: string
  fecha_llegada: string
  cliente_id: string
  operador_id: string
  caja_id: string
  tractor_id: string
  origen_id: string
  destino_id: string
  ventana_carga: string
  ventana_entrega: string
  kilometros: string
  combustible: string
  viaticos: string
  casetas: string
  regimen_aduanero: string
  referencia: string
  observaciones: string
  ErrorMovimientos: string
}
